- src/tests/count.spec.ts
- src/transforms/aggregation.ts
In some cases the aggregation Count did not return rows
> Fix aggregate count on empty selection

- src/adapters.ts
small bugfix, an undefined value now results in an error as `nullish (undefined === null)` =>` nullish (false)` => `false`
> small bugfix, an undefined value now results in an error

- src/datatypes/datatypes.ts
- src/interfaces.ts
- src/tests/various-expressions.spec.ts
This PR resolves a typo in the `timestamptz` implementation that was discovered in issue https://github.com/oguimbal/pg-mem/issues/68. It also adds a test case verifying the usage of the keyword.
> Fix timestamptz typo

- src/datatypes/t-timestamp.ts
- src/tests/datatypes.spec.ts
The Equality operator must use the absolute value of the difference
https://github.com/oguimbal/pg-mem/issues/71
> fix: TimestampType.doEquals

- src/column.ts
- src/interfaces-private.ts
- src/schema/readonly-table.ts
- src/table.ts
As a follow-up for #98, I propose to use a column manager which would be the central point to maintain this column list as:
- a map for the association of the name with the column definition;
- a column definition list (whose computation is cached);
When the map is mutated, the column definition list cache is invalidated.
I managed to remove the columnDefs, as the map values are ordered by their insertion time.
What do you think? (feedback welcome! :) )
> Introduce the column manager for tables

- src/adapters.ts
- src/interfaces.ts
- src/tests/knex-real.spec.ts
Hey! Great library.
This PR adds support to pass custom config to `knex`. I have a use case in which the `migration` folder has a different name than default `migrations` and `pg-mem` doesn't support it yet.
Any doubts let me know.
> update: forward knex config

- src/tests/aggregations.spec.ts
- src/transforms/aggregation.ts
- src/transforms/aggregations/array_agg.ts
❤️ to this library!
This is an initial implementation of an `array_agg` aggregation function since it does not support ordering inside. The ordering does not matter to me, just the function itself, so I thought that it can be merged like this (better than nothing) and then improved once refactoring is in place. If better to wait and have ordering support from scratch - feel free to reject this.
> Add array_agg support

- src/schema.ts
- src/tests/simple-queries.spec.ts
Autoincrement works when the column is a `serial` type, but fails when it's `bigserial`. Small modification to detect that data type in the table creation.
> Also flag serial (autoincrement) when the type is bigserial

- src/adapters.ts
- src/tests/pg.spec.ts
As explained in the issue, this allows inserting empty arrays with prepared statements :-)
Best,
> fixes #135, allowing insert empty arrays

- package.json
- src/datatypes/datatypes.ts
- src/datatypes/t-timestamp.ts
- src/expression-builder.ts
- src/schema/pg-catalog/index.ts
- src/tests/conversions.spec.ts
Update code to integrate precision support for timestamps offered by `pgsql-ast-parser@9.0.1`.
* Use existing `_registerTypeSizeable` solution to add precision support to the timestamp data type.
* Add unit test for type conversion to a timestamp with explicit precision.
Not sure why the package was called `pgsnpql-ast-parser` in `package.json`, but npm wouldn't install it so I changed it to the package's actual name. Let me know if this is intended and if I should revert my change.
> Add precision support to timestamps

- package-lock.json
- package.json
Running npm install under npm 8 was failing because of conflicting version constraints:
* package.json specified mocha ^8.0.1 and mochapack ^2.0.3
* and package-lock had pinned mochapack 2.0.3
* and mochapack 2.0.3 requires mocha <=7
This borked `npm install` (because npm got stricter about version conflicts):
```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: mochapack@2.0.3
npm ERR! Found: mocha@8.0.1
npm ERR! node_modules/mocha
npm ERR!   dev mocha@"^8.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mocha@">=6 <=7" from mochapack@2.0.3
npm ERR! node_modules/mochapack
npm ERR!   dev mochapack@"^2.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: mocha@7.2.0
npm ERR! …
```
> fix: version conflict between mocha and mochapack

- src/execution/select.ts
- src/interfaces.ts
- src/tests/select.queries.spec.ts
I found myself missing this in handling query results, and felt the simplest way to phrase the feature request was to write a test. I want to read both column names and types, for the query result.
Included is a draft implementation in `SelectExec` that satisfies this one test. But I notice that there is corresponding column naming logic in `src/transforms/selection.ts` with more involved name defaulting based on the column expressions, so I suspect probably that should be flowing through to the query result instead.
Fixes #234
> feat: populate QueryResult.fields with names and types

- src/schema/information-schema/index.ts
- src/schema/information-schema/table-constraints.ts
- src/schema/pg-catalog/index.ts
Fixes breakage with `sequelize@>=6.20.0`, see #227
> fix: create table_constraints in information_schema, not pg_catalog

- src/tests/select.queries.spec.ts
This draft PR currently just adds three test cases:
* a passing case showing the correct treatment of a query with a bogus column when no `ORDER BY` clause is present
* a failing case showing that a similar query with an `ORDER BY` clause doesn't throw an error; that's #228 
* a passing case (which _shouldn't_ pass!) showing the _current_ behavior of that latter query
> test: add cases illustrating issue #228

- src/interfaces.ts
This is to make sure sequelize could recognize it as the same way as pg:
https://github.com/sequelize/sequelize/blob/3b14f1aa70e3a3991891e37431344e6f0db0089c/src/dialects/postgres/query.js#L323
> Populate code property in QueryError to match pg behavior

- src/tests/order-by.queries.spec.ts
- src/transforms/order-by.ts
I discovered that `ORDER BY x ASC NULLS FIRST` did not work. This fixes that.
> fix: ORDER BY x ASC NULLS FIRST did not work

- src/column.ts
- src/tests/alter-table.queries.spec.ts
This should fix https://github.com/oguimbal/pg-mem/issues/340
TDD: The provided test fails without the provided fix.
Rationale: I have noticed that in many places in the code base after `this.table.db.onSchemaChange()` there is an invocation of `this.selection.rebuild()`. However this was not the case in this place.
> Rebuild alias on column rename

- src/datatypes/datatypes.ts
Allow Casting from Boolean to other types, specifically to `integer` in `pg-mem`
This pull request addresses the limitation in `pg-mem` where casting from boolean to integer is not allowed. This feature is important for providing complete emulation of PostgreSQL, which supports such casting.
- Updated the `BoolType` class in `datatypes.ts`.
- Modified the `doCanCast()` method to include `DataType.integer`  as allowable casting targets for booleans.
- Modified the `doCast()` method to correctly cast boolean values to integers (1 for `true`, 0 for `false`).
This change is necessary to ensure that `pg-mem` can emulate PostgreSQL as accurately as possible. The absence of this feature could lead to discrepancies between the behavior of `pg-mem` and PostgreSQL, especially when testing …
> feat: allowing bool casting

- src/execution/records-mutations/insert.ts
- src/interfaces-private.ts
- src/interfaces.ts
- src/table.ts
- src/tests/insert.queries.spec.ts
- src/tests/publicapi.spec.ts
when we use `insert .... on conflict do nothing`, and there is a conflict, nothing should be returned because no row was inserted. Fix the code accordingly.
See issue #353
> fix: nothing should be returned when using on conflict do nothing (#353)

- src/tests/select.queries.spec.ts
- src/transforms/alias.ts
Currently when you run a query against pg-mem with fully qualified column names like `SELECT "public"."test"."val" FROM "public"."test"`, it gives you an AST coverage error like `The query you ran generated an AST which parts have not been read by the query planner. This means that those parts could be ignored:  ⇨ .columns[0].expr.table.name ("test")`. This is happening because when the query planner retrieves the column data, in some cases it never actually checks the statement table name to be sure it matches before returning the column description. This commit refactors the column retrieval code to ensure this always gets checked.
I'm not familiar enough with the internal logic of this library to know if this fix is the "correct' way of doing this so I would like feedback on whether or …
> Fix AST coverage check error

- src/functions/sequence-fns.ts
- src/interfaces-private.ts
- src/schema/sequence.ts
- src/tests/sequence.spec.ts
The current implementation only accepts [two arguments](https://github.com/oguimbal/pg-mem/blob/master/src/functions/sequence-fns.ts#L57). However, in Postgres, a `setval` can have [three arguments](https://www.postgresql.org/docs/current/functions-sequence.html), and when using such queries, the `pg-mem` crashes.
This PR fixes this problem.
> Fix pg-mem crashes when setval has three arguments instead of two

- src/interfaces.ts
- src/schema/schema.ts
- src/tests/custom-types.spec.ts
I'm trying to extend pg-mem to support [pgvector](https://github.com/pgvector/pgvector), a popular library that's used for vector similarity search. 
The core feature of pgvector is a new column type "vector". 
Unfortunately, given the current API for pg-mem, I don't believe there is any way to implement vector (which is a *sizable* custom type). 
This pull request implements a new "registerEquivalentSizableType" that allows you to implement "vector". 
I'm not sure if this is the best way to implement this, so very open to feedback :)
> feat: add a sizable equivalent type

- src/tests/simple-queries.spec.ts
- src/transforms/eq-filter.ts
`EqFilter` class while working as expected in most conditions, didn't respect `matchNull` flag in cases when it was nested in secondary-order filters. This PR adds support for such `IS NULL` usage
> fix indexed column EqFilter condition for is null operator
